#!/bin/bash
pelican content -o output -s pelicanconf.py
ghp-import output -p -r https://github.com/hazelement/hazelement.github.io.git -b master
git push https://github.com/hazelement/hazelement.git gh-pages:master
